SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE JOINED LIKE '2021-%'),1) AS PUCHASED_RATIO
FROM USER_INFO U
JOIN ONLINE_SALE O ON O.USER_ID = U.USER_ID
WHERE U.JOINED LIKE '2021-%'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;

# Programmers 상품을 구매한 회원 비율 구하기 join 문제 풀이
