SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
LEFT JOIN ITEM_TREE T ON I.ITEM_ID = T.PARENT_ITEM_ID 
WHERE T.ITEM_ID IS NULL
GROUP BY I.ITEM_ID
ORDER BY ITEM_ID DESC;


# Programmers 업그레이드 할 수 없는 아이템 구하기 sql is null 문제 풀이
