SELECT O.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE *O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P
LEFT JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCE_DATE LIKE '2022-05-%'
GROUP BY PRODUCT_ID
ORDER BY 3 DESC, 1 ASC;

# Programmers join 문제 - 5월 식품들의 총매출 조회하기
